export const CREATE_SUBMISSION_REQUEST = 'CREATE_SUBMISSION_REQUEST';
export const CREATE_SUBMISSION_SUCCESS = 'CREATE_SUBMISSION_SUCCESS';
export const CREATE_SUBMISSION_FAILURE = 'CREATE_SUBMISSION_FAILURE';

export const GET_SUBMISSION_REQUEST = 'GET_SUBMISSION_REQUEST';
export const GET_SUBMISSION_SUCCESS = 'GET_SUBMISSION_SUCCESS';
export const GET_SUBMISSION_FAILURE = 'GET_SUBMISSION_FAILURE';

export const GET_SUBMISSIONS_REQUEST = 'GET_SUBMISSIONS_REQUEST';
export const GET_SUBMISSIONS_SUCCESS = 'GET_SUBMISSIONS_SUCCESS';
export const GET_SUBMISSIONS_FAILURE = 'GET_SUBMISSIONS_FAILURE';

export const UPDATE_SUBMISSION_REQUEST = 'UPDATE_SUBMISSION_REQUEST';
export const UPDATE_SUBMISSION_SUCCESS = 'UPDATE_SUBMISSION_SUCCESS';
export const UPDATE_SUBMISSION_FAILURE = 'UPDATE_SUBMISSION_FAILURE';

export const DELETE_SUBMISSION_REQUEST = 'DELETE_SUBMISSION_REQUEST';
export const DELETE_SUBMISSION_SUCCESS = 'DELETE_SUBMISSION_SUCCESS';
export const DELETE_SUBMISSION_FAILURE = 'DELETE_SUBMISSION_FAILURE';
