export const CREATE_EXERCISE_REQUEST = 'CREATE_EXERCISE_REQUEST';
export const CREATE_EXERCISE_SUCCESS = 'CREATE_EXERCISE_SUCCESS';
export const CREATE_EXERCISE_FAILURE = 'CREATE_EXERCISE_FAILURE';

export const GET_EXERCISE_REQUEST = 'GET_EXERCISE_REQUEST';
export const GET_EXERCISE_SUCCESS = 'GET_EXERCISE_SUCCESS';
export const GET_EXERCISE_FAILURE = 'GET_EXERCISE_FAILURE';

export const GET_EXERCISES_REQUEST = 'GET_EXERCISES_REQUEST';
export const GET_EXERCISES_SUCCESS = 'GET_EXERCISES_SUCCESS';
export const GET_EXERCISES_FAILURE = 'GET_EXERCISES_FAILURE';

export const UPDATE_EXERCISE_REQUEST = 'UPDATE_EXERCISE_REQUEST';
export const UPDATE_EXERCISE_SUCCESS = 'UPDATE_EXERCISE_SUCCESS';
export const UPDATE_EXERCISE_FAILURE = 'UPDATE_EXERCISE_FAILURE';

export const DELETE_EXERCISE_REQUEST = 'DELETE_EXERCISE_REQUEST';
export const DELETE_EXERCISE_SUCCESS = 'DELETE_EXERCISE_SUCCESS';
export const DELETE_EXERCISE_FAILURE = 'DELETE_EXERCISE_FAILURE';
